version: "3.7"

services:
  app:
    container_name: golden-app
    build: .
    ports:
    - 80:8080
    environment:
    - GOLDEN_DB_URL=devops22.cehxjqytwbqs.us-east-1.rds.amazonaws.com
    - GOLDEN_DB_NAME=goldendb
    - GOLDEN_DB_USERNAME=admin
    - GOLDEN_DB_PASSWORD=DevOps2022
    - GOLDEN_DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    networks:
    - goldendb-network

  db:
    container_name: goldendbsqldb
    image: mysql
    ports:
    - 80:3306
    environment:
      MYSQL_ROOT_PASSWORD: DevOps2022
      MYSQL_DATABASE: goldendb
    volumes:
    - goldendb-mysql:/var/lib/mysql
    - goldendb-mysql-config:/etc/mysql
    networks:
    - goldendb-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  goldenwaste-mysql:
  goldenwaste-mysql-config:

networks:
  goldendb-network:
    name: goldendb-network
    driver: bridge